In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px
from pywaffle import waffle
sns.set()

In [2]:
df=pd.read_csv('./books.csv',on_bad_lines='skip')
df.rename(columns={'  num_pages':'num_pages'},inplace=True)

In [3]:
df.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

## 1- What are the 10 most rated books (average rating)?

In [4]:
df.sort_values(by='average_rating',ascending=False)[['title','authors','average_rating']].head(10)

,title,authors,average_rating
624,Comoediae 1: Acharenses/Equites/Nubes/Vespae/P...,Aristophanes/F.W. Hall/W.M. Geldart,5.0
9893,His Princess Devotional: A Royal Encounter Wit...,Sheri Rose Shepherd,5.0
4788,The Diamond Color Meditation: Color Pathway to...,John Diamond,5.0
9324,Tyrannosaurus Wrecks (Stanley #1),Laura Driscoll/Alisa Klayman-Grodsky/Eric ...,5.0
9720,The Irish Anatomist: A Study of Flann O'Brien,Keith Donohue,5.0
4933,Bulgakov's the Master and Margarita: The Text ...,Elena N. Mahlow,5.0
6775,Delwau Duon: Peintiadau Nicholas Evans = Symph...,Nicholas Evans/Rhonda Evans,5.0
9282,Oliver Wendell Holmes in Paris: Medicine Theo...,William C. Dowling,5.0
786,Willem de Kooning: Late Paintings,Julie Sylvester/David Sylvester,5.0
4125,Zone of the Enders: The 2nd Runner Official St...,Tim Bogenn,5.0

## 2- Which book has the most ratings (ratings_count)?

In [5]:
index_max_ratings=df['ratings_count'].argmax()
df.iloc[index_max_ratings]

bookID                                    41865
title                   Twilight (Twilight  #1)
authors                         Stephenie Meyer
average_rating                             3.59
isbn                                 0316015849
isbn13                            9780316015844
language_code                               eng
num_pages                                   501
ratings_count                           4597666
text_reviews_count                        94265
publication_date                       9/6/2006
publisher             Little  Brown and Company
Name: 10336, dtype: object

## 3-Which book has the most pages?

In [6]:
most_pages=df['num_pages'].argmax()
most_pages
df.loc[most_pages]

bookID                                                         24520
title                 The Complete Aubrey/Maturin Novels (5 Volumes)
authors                                              Patrick O'Brian
average_rating                                                   4.7
isbn                                                      039306011X
isbn13                                                 9780393060119
language_code                                                    eng
num_pages                                                       6576
ratings_count                                                   1338
text_reviews_count                                                81
publication_date                                          10/17/2004
publisher                                      W. W. Norton  Company
Name: 6497, dtype: object

## 4 -What is the most used language in books?

In [7]:
most_lang_inBooks=df['language_code'].value_counts()
# most_lang_inBooks.index
# df.loc[df['language_code'].isin(most_lang_inBooks.index)]
most_lang_inBooks.reset_index().head()

  language_code  count
0           eng   8908
1         en-US   1408
2           spa    218
3         en-GB    214
4           fre    144

## 5- Which publishing houses have published the most books in this dataset?

## 6-Which author has the most books in the dataset?

In [8]:
# df['authors'].value_counts()
authors_group=df.groupby('authors')['title'].size().reset_index(name='size')
authors_group.sort_values(by='size',ascending=False)

                                            authors  size
5786                                   Stephen King    40
4747                                 P.G. Wodehouse    40
5470                               Rumiko Takahashi    39
4711                               Orson Scott Card    35
46                                  Agatha Christie    33
...                                             ...   ...
3066                       Joanne Harris/Fran Warde     1
811                    Carolyn Keene/Mildred Benson     1
812   Carolyn Keene/Russell H. Tandy/Mildred Benson     1
3063                                  Joanna Weaver     1
6638                          Éric-Emmanuel Schmitt     1

[6639 rows x 2 columns]

## 7 - Which author has the highest average rating for their books?

In [9]:
df['average_rating'].max()
average_g=df.groupby('authors')['average_rating'].value_counts().reset_index(name='counts')
average_g.sort_values(by='average_rating',ascending=False).head(22)

,authors,average_rating,counts
6885,NOT A BOOK,5.00,2
6792,Middlesex Borough Heritage Committee,5.00,1
2088,Dennis Adler/R.L. Wilson,5.00,1
4754,John Diamond,5.00,1
7012,Nicholas Evans/Rhonda Evans,5.00,1
3787,Ian Martin/Katie Elliott,5.00,1
1394,Chris Green/Chris Wright/Paul Douglas Gardner,5.00,1
8688,Sheri Rose Shepherd,5.00,1
5256,Julie Sylvester/David Sylvester,5.00,1
2486,Elena N. Mahlow,5.00,1
9228,Tara MacCarthy,5.00,1
7750,R. McL. Wilson,5.00,1
5458,Keith Donohue,5.00,1
9910,William C. Dowling,5.00,1
8398,Ross Garnaut,5.00,1
4151,James E. Campbell,5.00,1
5649,Laura Driscoll/Alisa Klayman-Grodsky/Eric ...,5.00,1
9474,Todd Davis/Marc Frey,5.00,1
9422,Tim Bogenn,5.00,1
8559,Sara Barton-Wood,5.00,1
615,Aristophanes/F.W. Hall/W.M. Geldart,5.00,1
8736,Simon Cleveland,4.91,1

In [10]:
# df['average_rating'].idxmax()
# df.iloc[624]
# df[df['authors']=='Aristophanes/F.W. Hall/W.M. Geldart']

df.iloc[df['average_rating'].idxmax()]

bookID                                                             2034
title                 Comoediae 1: Acharenses/Equites/Nubes/Vespae/P...
authors                             Aristophanes/F.W. Hall/W.M. Geldart
average_rating                                                      5.0
isbn                                                         0198145047
isbn13                                                    9780198145042
language_code                                                       grc
num_pages                                                           364
ratings_count                                                         0
text_reviews_count                                                    0
publication_date                                              2/22/1922
publisher                                  Oxford University Press  USA
Name: 624, dtype: object

## 8- Is there a relationship between the number of pages and the rating?

In [11]:
sns.scatterplot(data=df,y='num_pages',x='average_rating')
plt.xlim(left=(3,6))
plt.ylim(top=(500),bottom=0)
## no there is not relationship between the number of pages and the rating

(0.0, 500.0)

## 9 - Is there a relationship between the number of ratings and the number of text reviews?

In [12]:
df.head()
sns.lineplot(data=df,x='text_reviews_count',y='ratings_count',markers='o', lw=0.5)

## 10 - Do longer books get higher or lower ratings?

## 11 - What language books get the highest average ratings?